import { Frase } from '../shared/frase.model';

export const FRASES: Array<Frase> = [

  { fraseEng: 'I eat bread', frasePtBr: 'Eu como pão' },
  { fraseEng: 'I eat cheese', frasePtBr: 'Eu como queijo' },
  { fraseEng: 'I am fine', frasePtBr: 'Eu estou bem' },
  { fraseEng: 'I am hungry', frasePtBr: 'Eu estou com fome' },
  { fraseEng: 'I am sleeping', frasePtBr: 'Eu estou dormindo' },
  { fraseEng: 'I am happy', frasePtBr: 'Eu estou feliz' },
  { fraseEng: 'I am tired', frasePtBr: 'Eu estou cansado' },
  { fraseEng: 'I am angry', frasePtBr: 'Eu estou bravo' },
  { fraseEng: 'I am a student', frasePtBr: 'Eu sou estudante' },
  { fraseEng: 'I am a teacher', frasePtBr: 'Eu sou professor' },
  { fraseEng: 'I am a developer', frasePtBr: 'Eu sou desenvolvedor' },
  { fraseEng: 'You are a student', frasePtBr: 'Você é estudante' },
  { fraseEng: 'You are a teacher', frasePtBr: 'Você é professor' },
  { fraseEng: 'You are a developer', frasePtBr: 'Você é desenvolvedor' },
  { fraseEng: 'Are you fine?', frasePtBr: 'Você está bem?' },
  { fraseEng: 'Are you hungry?', frasePtBr: 'Você está com fome?' },
  { fraseEng: 'Are you sleeping?', frasePtBr: 'Você está dormindo?' },
  { fraseEng: 'Are you happy?', frasePtBr: 'Você está feliz?' },
  { fraseEng: 'Are you tired?', frasePtBr: 'Você está cansado?' },
  { fraseEng: 'Are you angry?', frasePtBr: 'Você está bravo?' },
  { fraseEng: 'Are you a student?', frasePtBr: 'Você é estudante?' },
  { fraseEng: 'Are you a teacher?', frasePtBr: 'Você é professor?' },
  { fraseEng: 'Are you a developer?', frasePtBr: 'Você é desenvolvedor?' },
  { fraseEng: 'I love you', frasePtBr: 'Eu amo você' },
  { fraseEng: 'I hate you', frasePtBr: 'Eu te odeio' },
  { fraseEng: 'How old are you?', frasePtBr: 'Quantos anos você tem?' },
  { fraseEng: 'Where are you from?', frasePtBr: 'você é de onde?' },
  { fraseEng: 'What is your name?', frasePtBr: 'Qual é o seu nome?' },
  { fraseEng: 'What is your job?', frasePtBr: 'Qual é o seu trabalho?' },
  { fraseEng: 'What is your hobby?', frasePtBr: 'Qual é o seu hobby?' },
  { fraseEng: 'What is your favorite food?', frasePtBr: 'Qual é o seu comida favorita?' },
  { fraseEng: 'What is your favorite color?', frasePtBr: 'Qual é o seu cor favorito?' },
  { fraseEng: 'What is your favorite movie?', frasePtBr: 'Qual é o seu filme favorito?' },
  { fraseEng: 'What is your favorite book?', frasePtBr: 'Qual é o seu livro favorito?' },
  { fraseEng: 'What is your favorite sport?', frasePtBr: 'Qual é o seu esporte favorito?' },
  { fraseEng: 'What is your favorite animal?', frasePtBr: 'Qual é o seu animal favorito?'  },
  { fraseEng: 'What is your favorite car?', frasePtBr: 'Qual é o seu carro favorito?' },
  { fraseEng: 'What is your favorite drink?', frasePtBr: 'Qual é o seu bebida favorita?'  },
  { fraseEng: 'Do you speak English?', frasePtBr: 'Você fala inglês?' },
  { fraseEng: 'do you speak other languages?', frasePtBr: 'você fala outras línguas?'},
  { fraseEng: 'do you speak Portuguese?', frasePtBr: 'você fala português?' },
  { fraseEng: 'What time is it?', frasePtBr: 'Que horas são?' },
  { fraseEng: 'Where is the nearest restaurant?', frasePtBr: 'Onde fica o restaurante mais próximo?' },
  { fraseEng: 'How do you get to the airport?', frasePtBr: 'Como você chega ao aeroporto?' },
  { fraseEng: 'Why are you late?', frasePtBr: 'Por que você está atrasado?' },
  { fraseEng: 'Can you help me?', frasePtBr: 'Você pode me ajudar?' },
  { fraseEng: 'Who is your best friend?', frasePtBr: 'Quem é seu melhor amigo?' },
  { fraseEng: 'Which book do you recommend?', frasePtBr: 'Qual livro você recomenda?' },
  { fraseEng: 'Whose car is parked outside?', frasePtBr: 'De quem é o carro estacionado lá fora?' },
  { fraseEng: 'Are you coming to the party?', frasePtBr: 'Você está vindo para a festa?' },
  { fraseEng: 'In my opinion, learning languages is important.', frasePtBr: 'Na minha opinião, aprender idiomas é importante.' },
  { fraseEng: 'According to the latest research, exercise improves memory.', frasePtBr: 'De acordo com as últimas pesquisas, o exercício melhora a memória.' },
  { fraseEng: 'As a student, I find math challenging.', frasePtBr: 'Como estudante, eu acho a matemática desafiadora.' },
  { fraseEng: 'After a long day at work, I like to relax and watch TV.', frasePtBr: 'Depois de um longo dia de trabalho, eu gosto de relaxar e assistir TV.' },
  { fraseEng: 'During the summer vacation, I plan to travel to Europe.', frasePtBr: 'Durante as férias de verão, eu planejo viajar para a Europa.' },
  { fraseEng: 'Before making a decision, I like to weigh the pros and cons.', frasePtBr: 'Antes de tomar uma decisão, eu gosto de pesar os prós e contras.' },
  { fraseEng: 'With the advancement of technology, communication has become easier.', frasePtBr: 'Com o avanço da tecnologia, a comunicação se tornou mais fácil.' },
  { fraseEng: 'Without a doubt, education is the key to success.', frasePtBr: 'Sem dúvida, a educação é a chave para o sucesso.' },
  { fraseEng: 'By learning from our mistakes, we can grow and improve.', frasePtBr: 'Aprendendo com nossos erros, podemos crescer e melhorar.' },
  { fraseEng: 'Through hard work and determination, anything is possible.', frasePtBr: 'Através do trabalho duro e da determinação, tudo é possível.' },
  { fraseEng: 'Have you ever been to Paris?', frasePtBr: 'Você já esteve em Paris?' },
  { fraseEng: 'What is the capital of Australia?', frasePtBr: 'Qual é a capital da Austrália?' },
  { fraseEng: 'How many siblings do you have?', frasePtBr: 'Quantos irmãos você tem?' },
  { fraseEng: 'Did you enjoy the movie?', frasePtBr: 'Você gostou do filme?' },
  { fraseEng: 'Where did you go on your last vacation?', frasePtBr: 'Para onde você foi em suas últimas férias?' },
  { fraseEng: 'Why did you choose this career path?', frasePtBr: 'Por que você escolheu essa carreira?' },
  { fraseEng: 'Can you recommend a good restaurant?', frasePtBr: 'Você pode me recomendar um bom restaurante?' },
  { fraseEng: 'Who is your favorite actor?', frasePtBr: 'Quem é o seu ator favorito?' },
  { fraseEng: 'Which country would you like to visit?', frasePtBr: 'Qual país você gostaria de visitar?' },
  { fraseEng: 'Whose phone is ringing?', frasePtBr: 'De quem é o telefone que está tocando?' },
  { fraseEng: 'After finishing my degree, I plan to travel the world.', frasePtBr: 'Depois de concluir minha graduação, planejo viajar pelo mundo.' },
  { fraseEng: 'In todays lesson, we will focus on grammar.', frasePtBr: 'Na aula de hoje, vamos focar em gramática.' },
  { fraseEng: 'During the winter season, I enjoy skiing with my friends.', frasePtBr: 'Durante a temporada de inverno, eu gosto de esquiar com meus amigos.' },
  { fraseEng: 'Before starting a new project, it is important to create a detailed plan.', frasePtBr: 'Antes de iniciar um novo projeto, é importante criar um plano detalhado.' },
  { fraseEng: 'With the rise of social media, staying connected has become easier.', frasePtBr: 'Com o aumento das redes sociais, manter-se conectado se tornou mais fácil.' },
  { fraseEng: 'Without proper training, it is difficult to excel in any sport.', frasePtBr: 'Sem um treinamento adequado, é difícil se destacar em qualquer esporte.' },
  { fraseEng: 'By volunteering at a local shelter, you can make a difference in someones life.', frasePtBr: 'Ao fazer trabalho voluntário em um abrigo local, você pode fazer a diferença na vida de alguém.' },
  { fraseEng: 'Through hard work and perseverance, you can achieve your goals.', frasePtBr: 'Através do trabalho duro e da perseverança, você pode alcançar seus objetivos.' },
  { fraseEng: 'With the support of my family, I was able to overcome challenges.', frasePtBr: 'Com o apoio da minha família, consegui superar desafios.' },
  { fraseEng: 'Without a doubt, learning a new language opens doors to new opportunities.', frasePtBr: 'Sem dúvida, aprender um novo idioma abre portas para novas oportunidades.' },
  { fraseEng: 'Do you enjoy cooking?', frasePtBr: 'Você gosta de cozinhar?' },
  // { fraseEng: 'What time is it?', frasePtBr: 'Que horas são?' },
  { fraseEng: 'Are you a morning person?', frasePtBr: 'Você é uma pessoa matutina?' },
  { fraseEng: 'Have you ever been skydiving?', frasePtBr: 'Você já praticou paraquedismo?' },
  { fraseEng: 'Which is your favorite season?', frasePtBr: 'Qual é a sua estação favorita?' },
  { fraseEng: 'Can you play a musical instrument?', frasePtBr: 'Você sabe tocar algum instrumento musical?' },
  { fraseEng: 'What is your favorite type of cuisine?', frasePtBr: 'Qual é o seu tipo de culinária favorito?' },
  { fraseEng: 'Did you watch any movies over the weekend?', frasePtBr: 'Você assistiu a algum filme no fim de semana?' },
  { fraseEng: 'Do you have any pets?', frasePtBr: 'Você tem algum animal de estimação?' },
  { fraseEng: 'Have you ever traveled abroad?', frasePtBr: 'Você já viajou para o exterior?' },
  { fraseEng: 'In my opinion, reading is a great way to relax.', frasePtBr: 'Na minha opinião, ler é uma ótima forma de relaxar.' },
  { fraseEng: 'During the summer months, I enjoy going to the beach.', frasePtBr: 'Durante os meses de verão, eu gosto de ir à praia.' },
  { fraseEng: 'With the rise of technology, communication has become easier.', frasePtBr: 'Com o avanço da tecnologia, a comunicação se tornou mais fácil.' },
  { fraseEng: 'Before making a decision, it is important to consider all the options.', frasePtBr: 'Antes de tomar uma decisão, é importante considerar todas as opções.' },
  { fraseEng: 'With hard work and determination, anything is possible.', frasePtBr: 'Com trabalho duro e determinação, tudo é possível.' },
  { fraseEng: 'By practicing regularly, you can improve your skills.', frasePtBr: 'Ao praticar regularmente, você pode melhorar suas habilidades.' },
  { fraseEng: 'Through collaboration, we can achieve great results.', frasePtBr: 'Através da colaboração, podemos alcançar ótimos resultados.' },
  { fraseEng: 'Without proper planning, it is difficult to accomplish your goals.', frasePtBr: 'Sem um planejamento adequado, é difícil alcançar seus objetivos.' },
  { fraseEng: 'With the support of my friends, I was able to overcome challenges.', frasePtBr: 'Com o apoio dos meus amigos, consegui superar desafios.' },
  { fraseEng: 'Without a doubt, education plays a key role in personal development.', frasePtBr: 'Sem dúvida, a educação desempenha um papel fundamental no desenvolvimento pessoal.' },
  { fraseEng: 'By learning from our mistakes, we can grow and improve.', frasePtBr: 'Aprendendo com nossos erros, podemos crescer e melhorar.' }

];
